# Generated by Django 2.0.6 on 2018-07-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
