# Generated by Django 2.0.6 on 2018-07-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_schedule_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='schedule_name',
        ),
    ]
