# Generated by Django 2.0.6 on 2018-07-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180722_2105'),
        # ('locations', '0012_auto_20180722_2105'),
        ('events', '0011_auto_20180722_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        # migrations.AddField(
        #     model_name='schedule',
        #     name='locations',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        # ),
    ]
