# Generated by Django 2.0.6 on 2018-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180722_2105'),
        ('locations', '0012_auto_20180722_2105'),
        ('events', '0012_auto_20180722_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employees',
        ),
        migrations.AddField(
            model_name='schedule',
            name='employees',
            field=models.ManyToManyField(to='employees.Employee'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='locations',
        ),
        migrations.AddField(
            model_name='schedule',
            name='locations',
            field=models.ManyToManyField(to='locations.Location'),
        ),
    ]
