# Generated by Django 2.0.6 on 2018-07-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180723_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
