# Generated by Django 2.0.6 on 2018-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('employees', '0003_auto_20180722_2105'),
        ('events', '0016_schedule_locations'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='schedule',
    #         name='employees',
    #         field=models.ManyToManyField(to='employees.Employee'),
    #     ),
    # ]
