# Generated by Django 2.0.6 on 2018-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180722_2105'),
        ('events', '0018_auto_20180723_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
