# Generated by Django 2.0.6 on 2018-07-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180722_2105'),
        ('employees', '0003_auto_20180722_2105'),
        ('events', '0019_auto_20180724_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(to='employees.Employee')),
                ('locations', models.ManyToManyField(to='locations.Location')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Schedule'),
        ),
    ]
