# Generated by Django 2.0.6 on 2018-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180722_2105'),
        ('events', '0020_auto_20180724_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='locations',
            field=models.ManyToManyField(to='locations.Location'),
        ),
    ]
