# Generated by Django 2.0.6 on 2018-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180722_2105'),
        ('events', '0021_schedule_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.ManyToManyField(to='locations.Position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
