# Generated by Django 2.0.6 on 2018-07-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180722_2105'),
        ('locations', '0012_auto_20180722_2105'),
        ('events', '0022_auto_20180724_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employees',
        ),
        migrations.AddField(
            model_name='shift',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.RemoveField(
            model_name='shift',
            name='locations',
        ),
        migrations.AddField(
            model_name='shift',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.RemoveField(
            model_name='shift',
            name='position',
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
