# Generated by Django 2.0.6 on 2018-07-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20180724_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='locations',
        ),
    ]
