# Generated by Django 2.0.6 on 2018-07-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_schedule_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_name',
        ),
    ]
