# Generated by Django 2.0.6 on 2018-07-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_schedule_schedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='schedule',
        ),
        migrations.AddField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
