# Generated by Django 2.0.6 on 2018-07-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180722_2105'),
        ('employees', '0003_auto_20180722_2105'),
        ('events', '0026_auto_20180724_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventShift',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.Position')),
                ('arrival_time', models.CharField(blank=True, max_length=256, null=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventLocation')),
            ],
            bases=('locations.position',),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='event_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventSchedule'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
