# Generated by Django 2.0.6 on 2018-07-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20180725_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='event_schedule_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
