# Generated by Django 2.0.6 on 2018-07-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_eventschedule_event_schedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='event_schedule_name',
        ),
    ]
