# Generated by Django 2.0.6 on 2018-07-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180722_2105'),
        ('locations', '0012_auto_20180722_2105'),
        ('events', '0030_auto_20180725_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventShift',
            new_name='Shift',
        ),
    ]
