# Generated by Django 2.0.6 on 2018-08-04 20:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20180803_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='alcohol',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
