# Generated by Django 2.0.6 on 2018-08-07 17:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20180804_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='schedule',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
