# Generated by Django 2.0.6 on 2018-08-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20180803_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='template',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EventTemplate',
        ),
    ]
