# Generated by Django 2.0.6 on 2018-08-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_template_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
    ]
