# Generated by Django 2.0.6 on 2018-08-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_schedule_event'),
        ('events', '0037_remove_event_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule'),
        ),
    ]
