# Generated by Django 2.0.6 on 2018-08-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_event_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='event_schedule',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='position_ptr',
        ),
        migrations.RemoveField(
            model_name='template',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventLocation',
        ),
        migrations.DeleteModel(
            name='EventSchedule',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
