# Generated by Django 2.0.6 on 2018-08-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20180815_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
    ]
