# Generated by Django 2.0.6 on 2018-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20180822_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.CharField(default='5:30PM', max_length=256, verbose_name='Event Start'),
            preserve_default=False,
        ),
    ]
