# Generated by Django 2.0.6 on 2018-08-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180722_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
