# Generated by Django 2.0.6 on 2018-08-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_companyprofilerole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofilerole',
            name='company_profile',
        ),
    ]
