# Generated by Django 2.0.6 on 2018-08-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0004_auto_20180822_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofilerole',
            name='color',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
