# Generated by Django 2.0.6 on 2018-08-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_companyprofilerole_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile'},
        ),
        migrations.AlterModelOptions(
            name='companyprofilerole',
            options={'verbose_name_plural': 'Company Profile Roles'},
        ),
    ]
