# Generated by Django 2.0.6 on 2018-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180702_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='positions',
            field=models.IntegerField(default=6),
        ),
    ]
