# Generated by Django 2.0.6 on 2018-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='positions',
            new_name='total_positions',
        ),
        migrations.AddField(
            model_name='location',
            name='manager_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='prep_position',
            field=models.BooleanField(default=False),
        ),
    ]
