# Generated by Django 2.0.6 on 2018-07-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20180703_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='locations.Location')),
            ],
        ),
    ]
