# Generated by Django 2.0.6 on 2018-07-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='manager_position',
        ),
        migrations.RemoveField(
            model_name='location',
            name='prep_position',
        ),
    ]
