# Generated by Django 2.0.6 on 2018-07-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20180704_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='total_positions',
        ),
        migrations.AlterField(
            model_name='position',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
