# Generated by Django 2.0.6 on 2018-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20180704_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_long',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
