# Generated by Django 2.0.6 on 2018-07-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_position_position_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='code',
        ),
    ]
