# Generated by Django 2.0.6 on 2018-07-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20180705_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bar',
            field=models.BooleanField(default=False),
        ),
    ]
