# Generated by Django 2.0.6 on 2018-07-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_location_bar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_id']},
        ),
    ]
