# Generated by Django 2.0.6 on 2018-08-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_auto_20180822_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='code',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='verbose_name',
        ),
    ]
