# Generated by Django 2.0.6 on 2018-08-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_auto_20180826_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
