# Generated by Django 2.0.6 on 2018-08-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_locationcategory_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationcategory',
            old_name='location_category',
            new_name='category',
        ),
    ]
