# Generated by Django 2.0.6 on 2018-08-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_auto_20180828_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcategory',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.LocationCategory'),
        ),
    ]
