# Generated by Django 2.0.6 on 2018-08-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_auto_20180828_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcategory',
            options={'verbose_name_plural': 'Location Categories'},
        ),
        migrations.RenameField(
            model_name='locationcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
