# Generated by Django 2.0.6 on 2018-08-09 17:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('template', models.BooleanField(default=False)),
                ('roster', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
