# Generated by Django 2.0.6 on 2018-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='Default Title', max_length=256),
            preserve_default=False,
        ),
    ]
