# Generated by Django 2.0.6 on 2018-08-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='scheduled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
