# Generated by Django 2.0.6 on 2018-08-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_schedule_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
