# Generated by Django 2.0.6 on 2018-08-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180822_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active_locations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
