# Generated by Django 2.0.6 on 2018-09-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_schedule_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created',
        ),
    ]
